name: Stock_Price_Prediction
dependencies:
  - python=3.11.0
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - pytest
  - pip
  - pip:
      - valkey
      - "valkey[hiredis]"
      - dvc[azure]
      - orjson
      - fastapi==0.100.0
      - pydantic==1.10.8
      - uvicorn[standard]==0.22.0
      - streamlit
      - requests
      - plotly
      - python-dotenv
