name: Stock_Price_Prediction
dependencies:
  - python=3.11.0
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - pytest
  - pip
  - pip:
      - valkey
      - "valkey[hiredis]"
      - dvc[azure]
      - langchain
      - langgraph
      - langchain-community
      - langchain-google-genai
      - langchain-pinecone
      - pinecone-notebooks
      - pinecone-client
      - streamlit
      - torch
      - chonkie
      - markitdown
