name: Stock_Price_Prediction
dependencies:
  - python=3.11.0
  - pandas
  - numpy
  - scikit-learn
  - jupyter
  - matplotlib
  - pytest
  - python-dateutil
  - pip
  - pip:
      - dvc[azure]
      - azure-cli
