name: Stock_Price_Prediction
dependencies:
  - python=3.11.0
  - pandas
  - numpy
  - scikit-learn
  - keras
  - statsmodels
  - pmdarima
  - jupyter
  - matplotlib
  - pytest
  - pydantic==1.10.8
  - pip
  - pip:
      - valkey
      - "valkey[hiredis]"
      - dvc[azure]
      - torch
      - orjson
      - fastapi==0.100.0
      - uvicorn[standard]==0.22.0
      - streamlit
      - requests
      - plotly
      - python-dotenv
      - requests_cache
      - langchain
      - langgraph
      - langchain-community
      - langchain-google-genai
      - pinecone-client
      - langchain-pinecone
      - pinecone-notebooks
      - azure-ai-ml
      - azure-identity
      - joblib
      - starlette>=0.27.0,<0.28.0
      - httpx>=0.23.1,<0.24.0