name: Stock_Price_Prediction
dependencies:
  - python=3.11.0
  - pandas
  - numpy
  - scikit-learn
  - keras
  - statsmodels
  - pmdarima
  - jupyter
  - matplotlib
  - pytest
  - pip
  - pip:
      - valkey
      - "valkey[hiredis]"
      - dvc[azure]
      - torch
      - orjson
