name: Python CI

on:
  pull_request:
    branches:
      - master  # Trigger on PRs targeting the `master` branch
      - main    # Trigger on PRs targeting the `main` branch

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.0'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Downgrade conda to 24.9.1
      run: |
        conda install conda=24.9.1
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        if find . -type f \( -name "test_*.py" -o -name "*_test.py" \) -exec grep -q "^def test_" {} +; then
          echo "Non-empty test files found. Running pytest..."
          cd tests
          pytest
        else
            echo "No valid tests to run (files are missing or empty)."
        fi