name: ETL Pipeline

on:
  workflow_dispatch:

jobs:
  ETL:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set Up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.0"

    - name: Install Conda 23.5.2
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh -O miniconda.sh
        bash miniconda.sh -b -p $HOME/miniconda
        echo "$HOME/miniconda/bin" >> $GITHUB_PATH

    - name: Create Conda Environment
      shell: bash -l {0}
      run: |
        source $HOME/miniconda/bin/activate
        conda init bash
        conda env create --file environment.yml --name Stock_Price_Prediction

    - name: Authenticate with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Extract Data
      run: |
          current_date=$(date +'%d-%m-%Y')
          source $HOME/miniconda/bin/activate
          conda activate Stock_Price_Prediction 
          python -m utils.download_automation --date $current_date
          dvc add data/raw/*.csv
          git config --global user.email "you@example.com"
          git config --global user.name "GitHub Actions"
          git add data/raw/*.dvc .dvc/.gitignore
          git commit -m "Add raw data for $current_date"

    - name: Transform data
      run: |
          source $HOME/miniconda/bin/activate
          conda activate Stock_Price_Prediction
          dvc pull
          python -m utils.process_stock_data
          dvc add data/processed/*.csv
          git add data/processed/*.dvc .dvc/.gitignore
          git commit -m "Update processed data for $current_date"

    - name: Load data
      run: |
          source $HOME/miniconda/bin/activate
          conda activate Stock_Price_Prediction
          dvc push
