name: Store News Articles

on: 
  workflow_dispatch:
    
env:
  KERAS_BACKEND: ${{ vars.KERAS_BACKEND }}
  MODEL_NAME: ${{ vars.MODEL_NAME }}
  WINDOW_SIZE: ${{ vars.WINDOW_SIZE }}
  MODEL_LOCATION: ${{ vars.MODEL_LOCATION }}
  MODEL_EVAL_THRESHHOLD: ${{ vars.MODEL_EVAL_THRESHHOLD }}
  AZURE_RESOURCE_GROUP:   ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_ML_WORKSPACE:     ${{ secrets.AZURE_ML_WORKSPACE }}
  SMTP_SERVER: ${{ vars.SMTP_SERVER }}
  SMTP_PORT: ${{ vars.SMTP_PORT }}
  SMTP_SENDER_EMAIL: ${{ vars.SMTP_SENDER_EMAIL }}
  SMTP_SENDER_PASSWORD: ${{ secrets.SMTP_SENDER_PASSWORD }}
  EMAIL_RECIPIENT: ${{ vars.EMAIL_RECIPIENT }}
  LANGSMITH_API_KEY:      ${{ secrets.LANGSMITH_API_KEY }}
  GOOGLE_API_KEY:         ${{ secrets.GOOGLE_API_KEY }}
  GOOGLE_API_KEY_1:       ${{ secrets.GOOGLE_API_KEY_1 }}
  USER_AGENT:             ${{ vars.USER_AGENT }}
  GENERATIVE_MODEL:       ${{ vars.GENERATIVE_MODEL }}
  SIMPLE_TASK_MODEL:      ${{ vars.SIMPLE_TASK_MODEL }}
  EMBEDDING_MODEL:        ${{ vars.EMBEDDING_MODEL }}
  PINECONE_API_KEY:       ${{ secrets.PINECONE_API_KEY }}
  INDEX_NAME:             ${{ secrets.INDEX_NAME }}
  
jobs:
  scrape-news:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.0"

      - name: Install Conda 23.5.2
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py311_23.5.2-0-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Create Conda Environment
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda init bash
          conda env create --file environment.yml --name Stock_Price_Prediction

      - name: Extract and Store News Articles
        run: |
            source $HOME/miniconda/bin/activate
            conda activate Stock_Price_Prediction 
            python -m scripts.news_scraper 