name: Azure ML Training Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.0"

      - name: Install Conda 23.5.2
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-py310_23.5.2-0-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      - name: Create Conda Environment
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda init bash
          conda env create --file environment.yml --name Stock_Price_Prediction

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Pull Latest Dataset from Azure Blob Storage
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda activate Stock_Price_Prediction
          dvc pull

      - name: Run Training Job
        shell: bash -l {0}
        run: |
          source $HOME/miniconda/bin/activate
          conda activate Stock_Price_Prediction
          
          # Set PYTHONPATH to include the project root
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          
          # Debug: Show the directory structure and PYTHONPATH
          echo "Current directory structure:"
          ls -la
          echo "PYTHONPATH: $PYTHONPATH"

          # Run the training script
          echo "Training model on Azure ML (To be implemented)"
